namespace BafflerStandalone.Forms.Options
{
	public partial class Options : global::System.Windows.Forms.Form
	{
#pragma warning disable 0649
		private global::System.ComponentModel.IContainer components = null;
		private global::System.Windows.Forms.GroupBox groupBox2;
		private global::System.Windows.Forms.Label label3;
		private global::System.Windows.Forms.TextBox tbOptAutoJoin;
		private global::System.Windows.Forms.Label label4;
		private global::System.Windows.Forms.ComboBox cbOptAlign;
		private global::System.Windows.Forms.TabControl tabControl1;
		private global::System.Windows.Forms.TabPage tabPage1;
		private global::System.Windows.Forms.TabPage tabPage2;
		private global::System.Windows.Forms.GroupBox groupBox1;
		private global::System.Windows.Forms.CheckBox checkBox1;
		private global::System.Windows.Forms.CheckBox checkBox2;
		private global::System.Windows.Forms.CheckBox checkBox3;
		private global::System.Windows.Forms.GroupBox groupBox3;
		private global::System.Windows.Forms.TextBox textBox2;
		private global::System.Windows.Forms.Label label6;
		private global::System.Windows.Forms.TextBox textBox1;
		private global::System.Windows.Forms.Label label5;
		private global::System.Windows.Forms.LinkLabel linkLabel1;
		private global::System.Windows.Forms.TabPage tabPage3;
		private global::System.Windows.Forms.ListView lvHotKeys;
		private global::System.Windows.Forms.ColumnHeader columnHeader3;
		private global::System.Windows.Forms.ColumnHeader columnHeader4;
		private global::System.Windows.Forms.Button button4;
		private global::System.Windows.Forms.Button button3;
		private global::System.Windows.Forms.Button button2;
		private global::System.Windows.Forms.Button button6;
		private global::System.Windows.Forms.Button button1;
		private global::System.Windows.Forms.Label label1;
		private global::System.Windows.Forms.Button button5;
		private global::System.Windows.Forms.TextBox textBox3;
		private global::System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
		private global::System.Windows.Forms.CheckBox checkBox4;
		private global::System.Windows.Forms.CheckBox checkBox5;
		
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			this.groupBox2 = new global::System.Windows.Forms.GroupBox();
			this.checkBox4 = new global::System.Windows.Forms.CheckBox();
			this.label3 = new global::System.Windows.Forms.Label();
			this.tbOptAutoJoin = new global::System.Windows.Forms.TextBox();
			this.label4 = new global::System.Windows.Forms.Label();
			this.cbOptAlign = new global::System.Windows.Forms.ComboBox();
			this.tabControl1 = new global::System.Windows.Forms.TabControl();
			this.tabPage1 = new global::System.Windows.Forms.TabPage();
			this.groupBox1 = new global::System.Windows.Forms.GroupBox();
			this.checkBox1 = new global::System.Windows.Forms.CheckBox();
			this.checkBox2 = new global::System.Windows.Forms.CheckBox();
			this.checkBox3 = new global::System.Windows.Forms.CheckBox();
			this.tabPage2 = new global::System.Windows.Forms.TabPage();
			this.groupBox3 = new global::System.Windows.Forms.GroupBox();
			this.checkBox5 = new global::System.Windows.Forms.CheckBox();
			this.label1 = new global::System.Windows.Forms.Label();
			this.button5 = new global::System.Windows.Forms.Button();
			this.textBox3 = new global::System.Windows.Forms.TextBox();
			this.textBox2 = new global::System.Windows.Forms.TextBox();
			this.label6 = new global::System.Windows.Forms.Label();
			this.textBox1 = new global::System.Windows.Forms.TextBox();
			this.label5 = new global::System.Windows.Forms.Label();
			this.linkLabel1 = new global::System.Windows.Forms.LinkLabel();
			this.tabPage3 = new global::System.Windows.Forms.TabPage();
			this.button4 = new global::System.Windows.Forms.Button();
			this.button3 = new global::System.Windows.Forms.Button();
			this.button2 = new global::System.Windows.Forms.Button();
			this.lvHotKeys = new global::System.Windows.Forms.ListView();
			this.columnHeader3 = new global::System.Windows.Forms.ColumnHeader();
			this.columnHeader4 = new global::System.Windows.Forms.ColumnHeader();
			this.button6 = new global::System.Windows.Forms.Button();
			this.button1 = new global::System.Windows.Forms.Button();
			this.folderBrowserDialog1 = new global::System.Windows.Forms.FolderBrowserDialog();
			this.groupBox2.SuspendLayout();
			this.tabControl1.SuspendLayout();
			this.tabPage1.SuspendLayout();
			this.groupBox1.SuspendLayout();
			this.tabPage2.SuspendLayout();
			this.groupBox3.SuspendLayout();
			this.tabPage3.SuspendLayout();
			base.SuspendLayout();
			this.groupBox2.Controls.Add(this.checkBox4);
			this.groupBox2.Controls.Add(this.label3);
			this.groupBox2.Controls.Add(this.tbOptAutoJoin);
			this.groupBox2.Controls.Add(this.label4);
			this.groupBox2.Controls.Add(this.cbOptAlign);
			this.groupBox2.Location = new global::System.Drawing.Point(15, 25);
			this.groupBox2.Name = "groupBox2";
			this.groupBox2.Size = new global::System.Drawing.Size(204, 159);
			this.groupBox2.TabIndex = 10;
			this.groupBox2.TabStop = false;
			this.groupBox2.Text = "General";
			this.checkBox4.AutoSize = true;
			this.checkBox4.Location = new global::System.Drawing.Point(9, 136);
			this.checkBox4.Name = "checkBox4";
			this.checkBox4.Size = new global::System.Drawing.Size(130, 17);
			this.checkBox4.TabIndex = 12;
			this.checkBox4.Text = "Snap to screen edges";
			this.checkBox4.UseVisualStyleBackColor = true;
			this.label3.AutoSize = true;
			this.label3.Location = new global::System.Drawing.Point(6, 31);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(94, 13);
			this.label3.TabIndex = 0;
			this.label3.Text = "Room to Auto-Join";
			this.tbOptAutoJoin.Location = new global::System.Drawing.Point(9, 47);
			this.tbOptAutoJoin.Name = "tbOptAutoJoin";
			this.tbOptAutoJoin.Size = new global::System.Drawing.Size(168, 20);
			this.tbOptAutoJoin.TabIndex = 1;
			this.label4.AutoSize = true;
			this.label4.Location = new global::System.Drawing.Point(6, 78);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(53, 13);
			this.label4.TabIndex = 2;
			this.label4.Text = "Alignment";
			this.cbOptAlign.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cbOptAlign.FormattingEnabled = true;
			this.cbOptAlign.Items.AddRange(new object[] {"No Align","Left","Right","LR","Top","Top Left","Top Right","LTR","Bottom","Bottom Left","Bottom Right","LRB","TB","LTB","TRB","LTRB"});
			this.cbOptAlign.Location = new global::System.Drawing.Point(9, 94);
			this.cbOptAlign.Name = "cbOptAlign";
			this.cbOptAlign.Size = new global::System.Drawing.Size(121, 21);
			this.cbOptAlign.TabIndex = 3;
			this.tabControl1.Controls.Add(this.tabPage1);
			this.tabControl1.Controls.Add(this.tabPage2);
			this.tabControl1.Controls.Add(this.tabPage3);
			this.tabControl1.Location = new global::System.Drawing.Point(12, 12);
			this.tabControl1.Name = "tabControl1";
			this.tabControl1.SelectedIndex = 0;
			this.tabControl1.Size = new global::System.Drawing.Size(469, 251);
			this.tabControl1.TabIndex = 11;
			this.tabPage1.BackColor = global::System.Drawing.SystemColors.Control;
			this.tabPage1.Controls.Add(this.groupBox1);
			this.tabPage1.Controls.Add(this.groupBox2);
			this.tabPage1.Location = new global::System.Drawing.Point(4, 22);
			this.tabPage1.Name = "tabPage1";
			this.tabPage1.Padding = new global::System.Windows.Forms.Padding(3);
			this.tabPage1.Size = new global::System.Drawing.Size(461, 225);
			this.tabPage1.TabIndex = 0;
			this.tabPage1.Text = "General";
			this.groupBox1.Controls.Add(this.checkBox1);
			this.groupBox1.Controls.Add(this.checkBox2);
			this.groupBox1.Controls.Add(this.checkBox3);
			this.groupBox1.Location = new global::System.Drawing.Point(241, 25);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new global::System.Drawing.Size(200, 159);
			this.groupBox1.TabIndex = 11;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Fullscreen";
			this.checkBox1.AutoSize = true;
			this.checkBox1.Location = new global::System.Drawing.Point(26, 31);
			this.checkBox1.Name = "checkBox1";
			this.checkBox1.Size = new global::System.Drawing.Size(155, 17);
			this.checkBox1.TabIndex = 6;
			this.checkBox1.Text = "Expand to fit entire desktop";
			this.checkBox1.UseVisualStyleBackColor = true;
			this.checkBox2.AutoSize = true;
			this.checkBox2.Location = new global::System.Drawing.Point(26, 68);
			this.checkBox2.Name = "checkBox2";
			this.checkBox2.Size = new global::System.Drawing.Size(104, 17);
			this.checkBox2.TabIndex = 7;
			this.checkBox2.Text = "Remove borders";
			this.checkBox2.UseVisualStyleBackColor = true;
			this.checkBox3.AutoSize = true;
			this.checkBox3.Location = new global::System.Drawing.Point(26, 104);
			this.checkBox3.Name = "checkBox3";
			this.checkBox3.Size = new global::System.Drawing.Size(99, 17);
			this.checkBox3.TabIndex = 8;
			this.checkBox3.Text = "Apply at startup";
			this.checkBox3.UseVisualStyleBackColor = true;
			this.checkBox3.Visible = false;
			this.tabPage2.BackColor = global::System.Drawing.SystemColors.Control;
			this.tabPage2.Controls.Add(this.groupBox3);
			this.tabPage2.Location = new global::System.Drawing.Point(4, 22);
			this.tabPage2.Name = "tabPage2";
			this.tabPage2.Padding = new global::System.Windows.Forms.Padding(3);
			this.tabPage2.Size = new global::System.Drawing.Size(461, 225);
			this.tabPage2.TabIndex = 1;
			this.tabPage2.Text = "Screenshots";
			this.groupBox3.Controls.Add(this.checkBox5);
			this.groupBox3.Controls.Add(this.label1);
			this.groupBox3.Controls.Add(this.button5);
			this.groupBox3.Controls.Add(this.textBox3);
			this.groupBox3.Controls.Add(this.textBox2);
			this.groupBox3.Controls.Add(this.label6);
			this.groupBox3.Controls.Add(this.textBox1);
			this.groupBox3.Controls.Add(this.label5);
			this.groupBox3.Controls.Add(this.linkLabel1);
			this.groupBox3.Location = new global::System.Drawing.Point(6, 6);
			this.groupBox3.Name = "groupBox3";
			this.groupBox3.Size = new global::System.Drawing.Size(439, 213);
			this.groupBox3.TabIndex = 12;
			this.groupBox3.TabStop = false;
			this.groupBox3.Text = "Screenshots";
			this.checkBox5.AutoSize = true;
			this.checkBox5.Location = new global::System.Drawing.Point(22, 80);
			this.checkBox5.Name = "checkBox5";
			this.checkBox5.Size = new global::System.Drawing.Size(135, 17);
			this.checkBox5.TabIndex = 8;
			this.checkBox5.Text = "Auto-Crop Screenshots";
			this.checkBox5.UseVisualStyleBackColor = true;
			this.checkBox5.Visible = false;
			this.label1.AutoSize = true;
			this.label1.Location = new global::System.Drawing.Point(19, 31);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(108, 13);
			this.label1.TabIndex = 7;
			this.label1.Text = "ScreenShot Directory";
			this.button5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.button5.Location = new global::System.Drawing.Point(395, 46);
			this.button5.Name = "button5";
			this.button5.Size = new global::System.Drawing.Size(29, 23);
			this.button5.TabIndex = 6;
			this.button5.Text = "...";
			this.button5.UseCompatibleTextRendering = true;
			this.button5.UseVisualStyleBackColor = true;
			this.button5.Click += new global::System.EventHandler(this.button5_Click);
			this.textBox3.Location = new global::System.Drawing.Point(22, 49);
			this.textBox3.Name = "textBox3";
			this.textBox3.Size = new global::System.Drawing.Size(366, 20);
			this.textBox3.TabIndex = 5;
			this.textBox2.Location = new global::System.Drawing.Point(22, 175);
			this.textBox2.Name = "textBox2";
			this.textBox2.Size = new global::System.Drawing.Size(198, 20);
			this.textBox2.TabIndex = 4;
			this.label6.AutoSize = true;
			this.label6.Location = new global::System.Drawing.Point(19, 158);
			this.label6.Name = "label6";
			this.label6.Size = new global::System.Drawing.Size(110, 13);
			this.label6.TabIndex = 3;
			this.label6.Text = "Filename Time Format";
			this.textBox1.Location = new global::System.Drawing.Point(22, 129);
			this.textBox1.Name = "textBox1";
			this.textBox1.Size = new global::System.Drawing.Size(124, 20);
			this.textBox1.TabIndex = 2;
			this.label5.AutoSize = true;
			this.label5.Location = new global::System.Drawing.Point(19, 109);
			this.label5.Name = "label5";
			this.label5.Size = new global::System.Drawing.Size(201, 13);
			this.label5.TabIndex = 1;
			this.label5.Text = "Filename prefix (leave empty for no prefix)";
			this.linkLabel1.AutoSize = true;
			this.linkLabel1.Location = new global::System.Drawing.Point(328, 187);
			this.linkLabel1.Name = "linkLabel1";
			this.linkLabel1.Size = new global::System.Drawing.Size(96, 13);
			this.linkLabel1.TabIndex = 0;
			this.linkLabel1.TabStop = true;
			this.linkLabel1.Text = "Screenshot Gallery";
			this.tabPage3.BackColor = global::System.Drawing.SystemColors.Control;
			this.tabPage3.Controls.Add(this.button4);
			this.tabPage3.Controls.Add(this.button3);
			this.tabPage3.Controls.Add(this.button2);
			this.tabPage3.Controls.Add(this.lvHotKeys);
			this.tabPage3.Location = new global::System.Drawing.Point(4, 22);
			this.tabPage3.Name = "tabPage3";
			this.tabPage3.Padding = new global::System.Windows.Forms.Padding(3);
			this.tabPage3.Size = new global::System.Drawing.Size(461, 225);
			this.tabPage3.TabIndex = 2;
			this.tabPage3.Text = "HotKeys";
			this.button4.Location = new global::System.Drawing.Point(376, 196);
			this.button4.Name = "button4";
			this.button4.Size = new global::System.Drawing.Size(75, 23);
			this.button4.TabIndex = 8;
			this.button4.Text = "Delete";
			this.button4.UseVisualStyleBackColor = true;
			this.button4.Click += new global::System.EventHandler(this.button4_Click);
			this.button3.Location = new global::System.Drawing.Point(270, 196);
			this.button3.Name = "button3";
			this.button3.Size = new global::System.Drawing.Size(75, 23);
			this.button3.TabIndex = 7;
			this.button3.Text = "Edit";
			this.button3.UseVisualStyleBackColor = true;
			this.button3.Click += new global::System.EventHandler(this.button3_Click);
			this.button2.Location = new global::System.Drawing.Point(189, 196);
			this.button2.Name = "button2";
			this.button2.Size = new global::System.Drawing.Size(75, 23);
			this.button2.TabIndex = 6;
			this.button2.Text = "New";
			this.button2.UseVisualStyleBackColor = true;
			this.button2.Click += new global::System.EventHandler(this.button2_Click);
			this.lvHotKeys.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[] {this.columnHeader3,this.columnHeader4});
			this.lvHotKeys.FullRowSelect = true;
			this.lvHotKeys.GridLines = true;
			this.lvHotKeys.Location = new global::System.Drawing.Point(6, 6);
			this.lvHotKeys.MultiSelect = false;
			this.lvHotKeys.Name = "lvHotKeys";
			this.lvHotKeys.ShowGroups = false;
			this.lvHotKeys.Size = new global::System.Drawing.Size(449, 184);
			this.lvHotKeys.TabIndex = 2;
			this.lvHotKeys.UseCompatibleStateImageBehavior = false;
			this.lvHotKeys.View = global::System.Windows.Forms.View.Details;
			this.columnHeader3.Text = "HotKey";
			this.columnHeader3.Width = 99;
			this.columnHeader4.Text = "Action";
			this.columnHeader4.Width = 317;
			this.button6.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			this.button6.Location = new global::System.Drawing.Point(366, 270);
			this.button6.Name = "button6";
			this.button6.Size = new global::System.Drawing.Size(111, 23);
			this.button6.TabIndex = 15;
			this.button6.Text = "Cancel Changes";
			this.button6.UseVisualStyleBackColor = true;
			this.button1.DialogResult = global::System.Windows.Forms.DialogResult.OK;
			this.button1.Location = new global::System.Drawing.Point(242, 270);
			this.button1.Name = "button1";
			this.button1.Size = new global::System.Drawing.Size(109, 23);
			this.button1.TabIndex = 14;
			this.button1.Text = "Save Settings";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Click += new global::System.EventHandler(this.button1_Click);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(493, 303);
			base.Controls.Add(this.button6);
			base.Controls.Add(this.button1);
			base.Controls.Add(this.tabControl1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			base.Name = "Options";
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Options - Baffler's Standalone";
			this.groupBox2.ResumeLayout(false);
			this.groupBox2.PerformLayout();
			this.tabControl1.ResumeLayout(false);
			this.tabPage1.ResumeLayout(false);
			this.groupBox1.ResumeLayout(false);
			this.groupBox1.PerformLayout();
			this.tabPage2.ResumeLayout(false);
			this.groupBox3.ResumeLayout(false);
			this.groupBox3.PerformLayout();
			this.tabPage3.ResumeLayout(false);
			base.ResumeLayout(false);
		}
	}
}
